function x = almostEqualHeaderStruct( header1,header2 )
%ALMOSTEQUALHEADERSTRUCT Compares the two header structs and returns 1 if all
%the header fields except for varName are equal, otherwise it returns 0

x = ...
isequal(header1.varUnits,header2.varUnits) &...
isequal(header1.dims,header2.dims) &...
isequal(header1.size,header2.size) &...
isequal(header1.origin,header2.origin) &...
isequal(header1.delta,header2.delta) &...
isequal(header1.label,header2.label) &...
isequal(header1.unit,header2.unit) &...
isequal(header1.precision,header2.precision) &...
isequal(header1.complex,header2.complex) &...
isequal(header1.distributed,header2.distributed);

end
